CREATE TABLE aula_02 (
    id   NUMBER
        GENERATED ALWAYS AS IDENTITY,
    nome VARCHAR2(30),
    data DATE
);


SELECT * FROM aula_02;

INSERT INTO AULA_02 (NOME, DATA) VALUES ('PAULO ', SYSDATE +3/24);
COMMIT;

